#development:
#  address: "smtp.example.com"
#  port: "25"
#  user_name: "user"
#  password: "password"
#  authentication: "plain" # plain, login, or cram_md5
#  domain: "example.com"
#  outgoing_address: "canvas@example.com"
#  default_name: "Instructure Canvas"

# or to use sendmail --
#
# development:
#   delivery_method: "sendmail"

#test:
#  delivery_method: "test"

#production:
#  delivery_method: "sendmail"
#  address: "smtp.gmail.com"
#  port: "587"
#  user_name: "tarcinrobotics301@gmail.com"
#  password: "tsixqrlycpmpxgck"
#  authentication: "plain" # plain, login, or cram_md5
#  domain: "gmail.com"
#  outgoing_address: "tarcinrobotics301@gmail.com"
#  default_name: "Tarcin Robotic LLP"
 
production:
  address: "localhost"
  port: "25"
  domain: "gmail.com"
  default_name: "Tarcin Robotic LLP"
  delivery_method: "sendmail"

multiple_inboxes:
  address: "smtp.gmail.com"
  port: "25"
  user_name: "tarcinrobotics301@gmail.com"   # mail id 
  password: "tsixqrlycpmpxgck"               # google app password generated by enabling two factor authentication
  authentication: "plain" # plain, login, or cram_md5
  domain: "gmail.com"
  outgoing_address: "tarcinrobotics301@gmail.com"   # mail id 
  default_name: "Tarcin Robotic LLP"                # name of the company which will appear in the mail sent
  reply_to_addresses:
  - "canvas1@example.com"
  - "canvas2@example.com"
  - "canvas3@example.com"
  - "canvas4@example.com"
